language: python

sudo: required

dist: trusty

before_install:
  - sudo sysctl -w net.ipv4.tcp_fin_timeout=15
  - sudo sysctl -w net.ipv4.tcp_tw_reuse=1
  - travis_retry curl -LO 'https://search.maven.org/remotecontent?filepath=org/kill-bill/billing/killbill-profiles-killbill/0.18.14/killbill-profiles-killbill-0.18.14-jetty-console.war' && java -Dorg.killbill.catalog.uri=SpyCarAdvanced.xml -Djava.security.egd=file:/dev/./urandom -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -jar killbill-profiles-killbill-0.18.14-jetty-console.war --port 8080 --headless 2>&1 | egrep -v "lvl='INFO'| < | > |[ \t]*at [ \ta-zA-Z0-9\.\:\(\)]+" & sleep 100 && travis_retry curl -v -X POST -u 'admin:password' -H 'Content-Type:application/json' -H 'X-Killbill-CreatedBy:admin' -d '{"apiKey":"bob", "apiSecret":"lazar"}' "http://127.0.0.1:8080/1.0/kb/tenants"

script: python -m unittest discover -s tests -v

notifications:
  email:
    - kill-bill-commits@googlegroups.com

python:
  - "2.7"
  - "3.6"
  - "pypy"
